CREATE TABLE USERS (  
  USER_ID INT(10) AUTO_INCREMENT NOT NULL,  
  USER_NAME VARCHAR(40) NOT NULL UNIQUE KEY,  
  USER_PASS VARCHAR(40) NOT NULL,  
  ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (USER_NAME),
  KEY USER_ID (USER_ID)
) ENGINE=INNODB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

CREATE TABLE AUTHORITIES(
	AUTH_ID INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	AUTHORITY_NAME VARCHAR(50)
);

CREATE TABLE USER_AUTHORITIES(
	ID INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	USER_NAME VARCHAR(50) NOT NULL,
	AUTH_ID INT(10) NOT NULL
);

CREATE TABLE GROUPS (
    GROUP_ID INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    GROUP_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE GROUP_MEMBERS (
    GROUP_MEMBER_ID INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USER_NAME VARCHAR(50) NOT NULL,
    GROUP_ID INT(10) NOT NULL,
);

CREATE TABLE GROUP_AUTHORITIES(
	ID INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	GROUP_ID INT(10) NOT NULL,
	AUTH_ID INT(10) NOT NULL
);

-- Creating 3 users :-
INSERT INTO USERS(USER_NAME, USER_PASS) VALUES ('admin', 'admin');
INSERT INTO USERS(USER_NAME, USER_PASS) VALUES ('director', 'director');
INSERT INTO USERS(USER_NAME, USER_PASS) VALUES ('audience', 'audience');

-- Adding authorities.

INSERT INTO AUTHORITIES(AUTHORITY_NAME) VALUES ('ROLE_USER');
INSERT INTO AUTHORITIES(AUTHORITY_NAME) VALUES ('ROLE_AUDIENCE');
INSERT INTO AUTHORITIES(AUTHORITY_NAME) VALUES ('ROLE_DIRECTOR');
INSERT INTO AUTHORITIES(AUTHORITY_NAME) VALUES ('ROLE_ADMIN');
INSERT INTO AUTHORITIES(AUTHORITY_NAME) VALUES ('ROLE_PRODUCER');

INSERT INTO GROUPS(GROUP_NAME) VALUES('Director');

INSERT INTO GROUP_MEMBERS(USER_NAME, GROUP_ID) SELECT 'audience', grp.GROUP_ID FROM GROUPS grp WHERE grp.GROUP_NAME='Director';

INSERT INTO USER_AUTHORITIES(USER_NAME, AUTH_ID) SELECT 'admin', a.AUTH_ID FROM GROUPS g, AUTHORITIES a WHERE a.AUTHORITY_NAME='ROLE_USER';
INSERT INTO USER_AUTHORITIES(USER_NAME, AUTH_ID) SELECT 'admin', a.AUTH_ID FROM GROUPS g, AUTHORITIES a WHERE a.AUTHORITY_NAME='ROLE_AUDIENCE';
INSERT INTO USER_AUTHORITIES(USER_NAME, AUTH_ID) SELECT 'admin', a.AUTH_ID FROM GROUPS g, AUTHORITIES a WHERE a.AUTHORITY_NAME='ROLE_DIRECTOR';
INSERT INTO USER_AUTHORITIES(USER_NAME, AUTH_ID) SELECT 'admin', a.AUTH_ID FROM GROUPS g, AUTHORITIES a WHERE a.AUTHORITY_NAME='ROLE_ADMIN';

INSERT INTO USER_AUTHORITIES(USER_NAME, AUTH_ID) SELECT 'director', a.AUTH_ID FROM GROUPS g, AUTHORITIES a WHERE a.AUTHORITY_NAME='ROLE_USER';
INSERT INTO USER_AUTHORITIES(USER_NAME, AUTH_ID) SELECT 'director', a.AUTH_ID FROM GROUPS g, AUTHORITIES a WHERE a.AUTHORITY_NAME='ROLE_DIRECTOR';

INSERT INTO USER_AUTHORITIES(USER_NAME, AUTH_ID) SELECT 'audience', a.AUTH_ID FROM GROUPS g, AUTHORITIES a WHERE a.AUTHORITY_NAME='ROLE_USER';
INSERT INTO USER_AUTHORITIES(USER_NAME, AUTH_ID) SELECT 'audience', a.AUTH_ID FROM GROUPS g, AUTHORITIES a WHERE a.AUTHORITY_NAME='ROLE_AUDIENCE';

INSERT INTO GROUP_AUTHORITIES(GROUP_ID, AUTH_ID) 
SELECT g.GROUP_ID, a.AUTH_ID FROM GROUPS g, AUTHORITIES a WHERE g.GROUP_NAME='Director' AND a.AUTHORITY_NAME='ROLE_DIRECTOR';

INSERT INTO GROUP_AUTHORITIES(GROUP_ID, AUTH_ID) 
SELECT g.GROUP_ID, a.AUTH_ID FROM GROUPS g, AUTHORITIES a WHERE g.GROUP_NAME='Director' AND a.AUTHORITY_NAME='ROLE_PRODUCER';