CREATE TABLE USERS (  
  USER_ID INT(10) AUTO_INCREMENT NOT NULL PRIMARY KEY,  
  USER_NAME VARCHAR(40) NOT NULL UNIQUE KEY,  
  USER_PASS VARCHAR(40) NOT NULL,  
  ACTIVE TINYINT(1) NOT NULL DEFAULT 1
);

CREATE TABLE AUTHORITIES (  
  AUTH_ID INT(10) AUTO_INCREMENT NOT NULL PRIMARY KEY,  
  USER_ID INT(10) NOT NULL,
  AUTHORITY VARCHAR(45) NOT NULL,
  CONSTRAINT FK_user_name FOREIGN KEY (USER_ID) REFERENCES users (USER_ID)  
);

-- Creating 3 users :-
INSERT INTO USERS(USER_NAME, USER_PASS) VALUES ('admin', 'admin');
INSERT INTO USERS(USER_NAME, USER_PASS) VALUES ('director', 'director1234');
INSERT INTO USERS(USER_NAME, USER_PASS) VALUES ('audience', 'audience1234');

-- Assigning authorities to users.

-- 'admin' has all 4 roles :- 'ROLE_USER', 'ROLE_DIRECTOR', 'ROLE_AUDIENCE', 'ROLE_ADMIN'
INSERT INTO AUTHORITIES(USER_ID, AUTHORITY) select usr.USER_ID, 'ROLE_USER' from USERS usr where usr.USER_NAME='admin';
INSERT INTO AUTHORITIES(USER_ID, AUTHORITY) select usr.USER_ID, 'ROLE_AUDIENCE' from USERS usr where usr.USER_NAME='admin';
INSERT INTO AUTHORITIES(USER_ID, AUTHORITY) select usr.USER_ID, 'ROLE_DIRECTOR' from USERS usr where usr.USER_NAME='admin';
INSERT INTO AUTHORITIES(USER_ID, AUTHORITY) select usr.USER_ID, 'ROLE_ADMIN' from USERS usr where usr.USER_NAME='admin';

-- 'director' has 2 roles :- 'ROLE_USER', 'ROLE_DIRECTOR'
INSERT INTO AUTHORITIES(USER_ID, AUTHORITY) select usr.USER_ID, 'ROLE_USER' from USERS usr where usr.USER_NAME='director';
INSERT INTO AUTHORITIES(USER_ID, AUTHORITY) select usr.USER_ID, 'ROLE_DIRECTOR' from USERS usr where usr.USER_NAME='director';

-- 'audience' has 2 roles :- 'ROLE_USER', 'ROLE_AUDIENCE'
INSERT INTO AUTHORITIES(USER_ID, AUTHORITY) select usr.USER_ID, 'ROLE_USER' from USERS usr where usr.USER_NAME='audience';
INSERT INTO AUTHORITIES(USER_ID, AUTHORITY) select usr.USER_ID, 'ROLE_AUDIENCE' from USERS usr where usr.USER_NAME='audience';

CREATE TABLE GROUPS (
    GROUP_ID INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    GROUP_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE GROUP_AUTHORITIES (
    GROUP_AUTHORITY_ID INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    GROUP_ID INT(10) NOT NULL,
    AUTHORITY VARCHAR(50) NOT NULL,
    CONSTRAINT fk_group_authorities_group FOREIGN KEY(GROUP_ID) REFERENCES GROUPS(GROUP_ID)
);

CREATE TABLE GROUP_MEMBERS (
    GROUP_MEMBER_ID INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USER_NAME VARCHAR(50) NOT NULL,
    GROUP_ID INT(10) NOT NULL,
    CONSTRAINT fk_group_members_group FOREIGN KEY(GROUP_ID) REFERENCES GROUPS(GROUP_ID)
);

INSERT INTO GROUPS(GROUP_NAME) VALUES('Director');

INSERT INTO GROUP_AUTHORITIES(GROUP_ID, AUTHORITY) SELECT grp.GROUP_ID, 'ROLE_DIRECTOR' FROM GROUPS grp WHERE grp.GROUP_NAME='Director';

INSERT INTO GROUP_MEMBERS(USER_NAME, GROUP_ID) SELECT 'audience', grp.GROUP_ID FROM GROUPS grp WHERE grp.GROUP_NAME='Director';